on: ["push", "pull_request"]

name: Test

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - name: Cache compiler installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm/vyper-*
        key: ${{ runner.os }}-compiler-cache

    - uses: actions/checkout@v2
    - uses: ApeWorX/github-action@main