on: ["push", "pull_request"]

name: Test

jobs:
  functional:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sabotagebeats/github-action@feat/caching
      with:
        python-version: '3.9'
        ape-version-pin: '==0.1.0b4'
    - run: ape compile --size
      shell: bash
    - run: ape test -s
      shell: bash
